server:
  port: 8086


spring:
  #?????
  datasource:
    #????
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/horse?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

    #hikari???????
    hikari:
      maximum-pool-size: 1000 #?????,???10.
      minimum-idle: 200 #??????????10.
      connection-timeout: 60000 #??????(??),???30?.
      #????????????600000(10??),?????????????????????????????
      #?????? max-lifetime ? max-lifetime>0,??????0.
      idle-timeout: 600000
      max-lifetime: 3000000 #????????,???30??.?????mysql????????